### ISSUE TITLE
torch hub silero_vad example breaks due to `get_speech_ts` refactoring

### ISSUE THREAD

**Issue by vmoens** [snakers4/silero-vad#136]
## 🐛 Bug

Torch hub [silero_vad example](https://github.com/pytorch/hub/blob/94f0352e30c87b32525e9c2edf191d2c429591df/snakers4_silero-vad_vad.md?plain=1#L41-L42) still uses `get_speech_ts`, which used to have a `num_steps` argument. The refactored `get_speech_timestamp` does not, hence the example breaks.
A quick fix could simply be to remove the arg (which I did [here](https://github.com/pytorch/hub/pull/261/commits/6be0bc76d75f2f58be6b2d24545345f05fcc9033)) but I'd rather make sure that this is ok before merging.

## To Reproduce

Run example in [snakers4_silero-vad_vad.md](https://github.com/pytorch/hub/blob/master/snakers4_silero-vad_vad.md).

**Comment by snakers4** [comment]
Many thanks for keeping up with the examples!

Since we published the VAD on `torch_hub`, we saw little activity from there for the VAD, so we forgot to update the example during this release, since we too much focused on making the VAD more simple (we had made it too complex, with different sampling rates, versions and sizes etc etc).

As for your fix, it should be ok, if it runs. The only issue is that now the `jit` VAD accepts both 8k and 16k inputs.

So maybe adding this to the VAD example would make sense:

```
...
SAMPLE_RATE = 16000  # also accepts 8000
wav = read_audio(f'{files_dir}/en.wav', sampling_rate=SAMPLE_RATE)
speech_timestamps = get_speech_timestamps(wav, model, sampling_rate=SAMPLE_RATE)  # see docstring for other sampling rates
```
Note that the [docstring ](https://github.com/snakers4/silero-vad/blob/master/utils_vad.py#L71) describes how to choose chunk size properly (I guess we did not express it in milliseconds for a reason, I will ask why).

Examples now live here btw:

- https://github.com/snakers4/silero-vad/wiki/Examples-and-Dependencies#dependencies
- https://github.com/snakers4/silero-vad/wiki/Other-Models

**Comment by snakers4** [comment]
> Note that the docstring describes how to choose chunk size properly (I guess we did not express it in milliseconds for a reason, I will ask why).

Yeah, rounding issues, did not think about it when doing the R&D, so now the param is in samples.

**Comment by vmoens** [comment]
Ok thanks for the quick reply! We've update torch hub scripts accordingly.

**Comment by snakers4** [comment]
My colleague who has authored the last update took a look at the above PR, also looks fine to him
