### ISSUE TITLE
Feature request: `get_speech_timestamps()` visualize_probs: Please allow us to pass a subplot / ax

### ISSUE THREAD

**Issue by schittli** [snakers4/silero-vad#325]
Hello

**Thank you so much for sharing your great work!**

## 🚀 Feature

The function `get_speech_timestamps()` is able to visualize the speech probability by using `visualize_probs=True`
Please allow us to pass a subplot / ax to the function, so that the visualization will be plottet on it.

## Motivation

- As soon as a user needs to check the speech probability, then it always helps to see additional information on the same x-axis, e.g. the audio signal.
- If the user needs to adjust the threshold for `get_speech_timestamps()`, then the only reasonable way is to display the speech probability in parallel with the audio signal.
- If the input signal has a bad signal / noise ratio, then it helps a lot to have the audio signal on the same x-axis with the speech probability, so that input signal is not cleaned up too much.

## Pitch

It would be great if there is simple and fast way to determine the threshold for `get_speech_timestamps()`
Therefore it helps a lot if the speech probability and the audio signal can be plotted on the same x-axis.

It also helps a lot to check if the input signal is good enough for silero vad, e.g. to see if the signal / noise ration is OK.

The solution should be flexible, because sometimes one would like to ad multiple subplots on the same x-axis of the speech probability, e.g. display the stereo wav file on separate subplots for each channel or add additional information on additional subplots.

## Alternatives

I have no idea how to solve it differently in Python.

**Comment by snakers4** [comment]
Hi,

This seems like a nice feature, though a bit niche, probably because not many people use the plot anyway.

In any case a PR would be appreciated, I guess it would make sense to separate the plotting function into a separate function at least.

Usually I would do this via `kwargs`, but here I am not sure how to do it, without bloating the docstring.

**Comment by jonnor** [comment]
I would propose to add a function which allows getting just the speech probabilities. That would allow plotting or processing them in any manner the API consumer sees fit. This could be internally reused in the existing get_speech_timestamps (which also does the post-processing).
I ended up creating such a function myself, in order to get the probabilities.
