### ISSUE TITLE
speech_pad_ms may cause start position to be a negative number

### ISSUE THREAD

**Issue by forthcoming** [snakers4/silero-vad#500]
```
model = load_silero_vad()
vad_iterator = VADIterator(model, sampling_rate=16000, speech_pad_ms=20)
```
If there is a human voice at the beginning of the audio, the ideal value of start is 0, but when speech_pad_ms=20, start will become a negative number.
If you want to reproduce it quickly, just increase the value of speech_pad_ms, because start may not be 0 at the beginning.

**Comment by adamnsandle** [comment]
Hi! Fixed this bug in the repo.
pip version will be fixed in future releases.
**Reminder!** VADIterator class exists for example purpose only. 
If you want to annotate the entire audio file use the `get_speech_timestamps` method
VADIterator is a good example boilerplate for real time streaming, nothing more
